### ISSUE TITLE
Can not install addon

### ISSUE THREAD

**Issue by thorstone137** [deliciousbrains/wp-migrate-db-pro-bugs#10] opened 2013-12-07 18:29 UTC
Whether I'm in production or local I get this when I click the install button..

![2013-12-07_1227](https://f.cloud.github.com/assets/343876/1698865/6234f666-5f6d-11e3-8f5c-cd47fd3a28f8.png)

**Comment by bradt** [comment] 2013-12-07 19:36
Duplicate of #1

**Closed as completed by bradt** 2013-12-07 19:36 UTC
