### ISSUE TITLE
Cannot install plugin locally

### ISSUE THREAD

**Issue by tordans** [deliciousbrains/wp-migrate-db-pro-bugs#7] opened 2013-12-06 12:53 UTC
I dont have a local ftp-server so for my local instance I install my plugins by manually by downloading them into the folder.
I cannot to this with the sub-plugins ATM since there is no download button. – So there should be one :).

![bildschirmfoto 2013-12-06 um 13 53 24](https://f.cloud.github.com/assets/111561/1692224/6f0bbcce-5e75-11e3-9c9c-d38e1b0d09e4.png)

**Comment by bradt** [comment] 2013-12-06 18:37
Good idea. We'll add that to our todo list.

**Comment by aprea** [comment] 2013-12-10 22:25
Closing this issue for now, we'll be releasing an update for this soon, please feel free to raise another issue if the problem is still relevant after the update.

**Closed as completed by aprea** 2013-12-10 22:25 UTC
